name: Digital Significa Personas
favicon: null
layout_spectrum: 0.3600539283361286
typography_spectrum: 0.1729559504892677
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4375
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 0.20987171586602926
purpose: []
